### ISSUE TITLE
displaying property 

### ISSUE THREAD

**Issue by tristan-salles** [ericbdaniels/jupyter-dash-vtk-viewer#1] opened 2021-05-17 00:10 UTC
Hi @ericbdaniels, looks pretty cool. 

Would you have an example on how to display the property fields in the viewer? I tried loading a vtk file 

```
mesh = pv.read(vtkfile)
mesh.name = 'test' 
mesh.array_names 
```

which returns
`['elev', 'erodep', 'rain', 'FA', 'SL', 'fill', 'basin']`

but the viewer doesn't show any arrays to select. Is there any option to put in the viewer function to select specific values to display. With Pyvista I would have done something like:

```
mesh = pv.read(vtkfile)
plot = pv.PlotterITK()
plot.add_mesh(mesh, scalars="elev")
plot.show()
```

**Comment by ericbdaniels** [comment] 2021-05-17 01:32
hi @tristan-salles, glad you gave it a try.

Forgive me - this is a bit of a work in progress and scraped together in my little bit of spare time and fit for purpose as needed in my day job.

I suspect the data you're wanting to display is point located. Thus far I've only used this viewer for cell located data arrays.

heres an example:
![image](https://user-images.githubusercontent.com/6198000/118420584-74fefd00-b67c-11eb-948d-784471230d27.png)

Just to confirm, when you have a moment please try `mesh.point_arrays` to check if those `mesh.array_names` are indeed listed.

Should you feel inspired to tinker with it a bit, I believe the issue is in components.py lines 8-13

```python 
def grid_controls(vtkobj):
    """controls specific to each vtk object"""
    field_name_options = []
    color_by_disabled = True
    cell_data = vtkobj.GetCellData()    
    data_names = [cell_data.GetArrayName(i) for i in range(cell_data.GetNumberOfArrays())]```

**Comment by ericbdaniels** [comment] 2021-05-17 01:32
also, I'll push this example in case its any help

**Comment by tristan-salles** [comment] 2021-05-17 01:53
Awesome, thanks for the quick reply!

This:

```
viewmesh = mesh.point_data_to_cell_data()
cell_data = viewmesh.GetCellData()  
data_names = [cell_data.GetArrayName(i) for i in range(cell_data.GetNumberOfArrays())]
print(data_names)

viewer.inline(mesh,contour)
```

works perfectly!
<img width="1378" alt="Screen Shot 2021-05-17 at 11 52 35 am" src="https://user-images.githubusercontent.com/7201912/118422382-77a63480-b706-11eb-9152-ba25d5f074cb.png">

**Comment by ericbdaniels** [comment] 2021-05-19 17:19
@tristan-salles , I added updated to support point located data - hopefully makes your life easier.

![mtsthelens](https://user-images.githubusercontent.com/6198000/118856345-13b17680-b894-11eb-8c43-baa8a1244fc5.png)

I'll go ahead and close this issue - if you run into other problems, please let me know. 
Thanks

**Closed by ericbdaniels** 2021-05-19 17:19 UTC
